# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
title: UMD Accessibility Testing Workshops
description: >- # this means to ignore newlines until "baseurl:"
  This site provides a home for test cases and sample website content to facilitate
  accessibility testing workshops and homework hosted by the University of Maryland.
baseurl: "/umdA11yWorkshops" # the subpath of your site, e.g. /blog
url: "https://section508coordinators.github.io" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - package-lock.json
  - pakage.json
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - gulpfile.js
  - LICENSE

primary_navigation:
  - name: Home
    url: /
  - name: Demo
    url: /demo/
  - name: Homework 1
    url: /homework-1/
  - name: Homework 2
    url: /homework-2/

collections:
  testcases:
    output: true
    permalink: :collection/:name/
  testfiles:
    output: true